# 子服标识，先配置这个
server: "lobby"

# 聊天管理
chat:
  # 是否开启
  enable: true
  # 聊天格式 支持变量
  format:
    # 聊天前缀
    prefix:
        text: '[%ip2region_provincial%]%playerTitle_use%'
        hover:
          - '&8▪ &6称号数量: %playerTitle_number%'
          - '&8▪ &6称号币数量: %playerTitle_coin%'
    # 聊天玩家名
    player:
        text: '&f%player_name%'
        hover:
          - '&8▪ &6所在世界: %multiverse_world_alias%'
          - '&8▪ &6所属公会: %playerGuild_name%'
          - '&8▪ &6任务币: %playerTask_coin%'
          - '&8▪ &6精英币: %elitemobs_player_money%'
          - '&8▪ &6精英等级: %elitemobs_player_active_guild_rank_name%'
          - '&8▪ &6战斗等级:  %elitemobs_player_combat_tier%'
    # 聊天内容
    msg:
      text: '&f'
      hover:
        - '&7时间: %server_time_h:mm:ss a%'

# 喇叭管理
lb:
  # 喇叭的类型-要保证唯一
  全服大喇叭:
    name: "&#FF0000全&#FF0033服&#FF0066大&#FF0099喇&#FF00B4叭"
    enable: true
    rgb: "&#FF0000"
    # 喇叭服务器范围
    server:
      - "lobby1"
      - "pvp"
    # 文本消息
    message:
      enable: true
      format:
        - "&a------------------------"
        - "${message}"
        - "&a------------------------"
    # 物品栏上方消息
    actionbar:
      enable: true
      rgb: "&a"
    # boss血条消息
    boss:
      enable: true
      # 血条颜色 https://bukkit.windit.net/javadoc/org/bukkit/boss/BarColor.html
      color: "PINK"
      # 血条样式 https://bukkit.windit.net/javadoc/org/bukkit/boss/BarStyle.html
      style: "SOLID"
      time: 3
    # 公告消息
    title: true