# 子服标识，群组服需先配置这个
server: "lobby"

# 第一次修改语言文件,需重启生效
language: zh_CN

# 是否开启更新提醒,建议开启
isCheckUpdate: true

# op登录时候是否发送更新提醒
isCheckUpdateToOpMsg: true

# 聊天冷却时间(单位秒)(可无限扩展和修改子节点，权限格式: playerChat.chatTime.vip1)
chatTime:
  # 默认玩家的时间
  default: 3
  # vip1的上限 需要权限 playerWarp.delayTime.vip1
  vip1: 2
  # vip2的上限 需要权限 playerWarp.delayTime.vip2
  vip2: 1
  # vip3的上限 需要权限 playerWarp.delayTime.vip3
  vip3: 0

# 黑名单,关键字替换成*
blacklist:
  - '操'
  - '草'
  - 'cao'