# 子服标识，先配置这个
server: "lobby"

lb:
  # 喇叭的类型-要保证唯一
  全服大喇叭:
    name: "&#FF0000全&#FF0033服&#FF0066大&#FF0099喇&#FF00B4叭"
    enable: true
    rgb: "&#FF0000"
    server:
      - "lobby1"
      - "pvp"
    message:
      enable: true
      format:
        - "&a------------------------"
        - "${message}"
        - "&a------------------------"
    actionbar:
      enable: true
      rgb: "&a"
    boss:
      enable: true
      color: "PINK"
      style: "SOLID"
      time: 3
    title: true