name: PlayerChat
main: cn.handyplus.chat.PlayerChat
version: 1.0.6
author: handy
api-version: 1.13
softdepend: [ PlaceholderAPI ]
website: https://ricedoc.handyplus.cn/wiki/PlayerChat/log/
description: 米饭聊天
commands:
  playerChat:
    description: 米饭聊天
    aliases: [ plc ]
  lb:
    description: 米饭聊天
    aliases: [ lb ]
permissions:
  playerChat.*:
    description: 大喇叭
    children:
      playerChat.reload: true
      playerChat.give: true
      playerChat.take: true
      playerChat.set: true
      playerChat.look: true
      playerChat.color: true
      playerChat.channel: true
  playerChat.reload:
    description: 重新加载配置
    default: op
  playerChat.give:
    description: 给予喇叭
    default: op
  playerChat.take:
    description: 拿走喇叭
    default: op
  playerChat.set:
    description: 设置喇叭
    default: op
  playerChat.look:
    description: 查看喇叭
    default: op
  playerChat.color:
    description: 颜色权限
    default: op
  playerChat.channel:
    description: 切换渠道
    default: op